# Generated by Django 4.2.4 on 2023-09-03 14:17

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_callbackform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[100, 100], upload_to='ava/')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tour', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='tourgalleryimage',
            options={'ordering': ('is_main',), 'verbose_name': 'Картинка галерей', 'verbose_name_plural': 'Картинки галерей'},
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[840, 580], upload_to='fb/gallery')),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.feedback')),
            ],
            options={
                'verbose_name': 'Картинка отзыва',
                'verbose_name_plural': 'Картинки отзывов',
            },
        ),
    ]
