# Generated by Django 4.2.4 on 2023-09-25 11:43

import ckeditor_uploader.fields
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_feedback_alter_tourgalleryimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[120, 200], upload_to='fb/gallery'),
        ),
    ]
